### PR TITLE
[TECHNICAL-SUPPORT] LPS-56833

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by yuhai** [comment]
Hi Igor,

Hope you are doing well.

Could you please take the PR as high priority? Because the issue came from EE customer.

Regards,
Hai

**Comment by hhuijser** [comment]
Hey @igorspasic 

Can you please give this priority and review?

Thanks!

**Comment by igorspasic** [comment]
unfortunately, not at the moment, as soon as I come back from vacation.

**Comment by hhuijser** [comment]
Sent to @csierra instead: https://github.com/csierra/liferay-portal/pull/84

**Pull request closed without merging**
