### PR TITLE
LPS-56624 Use the servlet context name instead of manufacturing one

### PR DESCRIPTION
**Pull request by nhpatt**
Resending https://github.com/igorspasic/liferay-portal/pull/81 because configuration problems in testing

### CODE REVIEW

**Comment by igorspasic** [comment]
Just started reviewing :)<br>:rocket:

**Comment by igorspasic** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/27855.<br>:rocket:

**Comment by nhpatt** [comment]
I've talked with @mdelapenya and he is going to check what is wrong with the commit/pull

**Comment by igorspasic** [comment]
Just started reviewing :)<br>:rocket:

**Comment by igorspasic** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/27896.<br>:rocket:

**Comment by igorspasic** [comment]
Hey @nhpatt, my PR is also not getting tested. Did you managed to work it out?

**Comment by nhpatt** [comment]
Yep, I saw it, Manuel is looking at it, so we'll have to wait until he
finds something.

Un saludo,

Javier Gamarra

**Pull request closed without merging**
