### PR TITLE
LPS-56734

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @igorspasic 

Can you review and send to Brian if this looks okay to you?

Thanks!

**Comment by igorspasic** [comment]
Just started reviewing :)<br>:rocket:

**Comment by igorspasic** [comment]
Just started reviewing :)<br>:rocket:

**Comment by igorspasic** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/27854.<br>:rocket:

**Comment by igorspasic** [comment]
Just started reviewing :)<br>:rocket:

**Comment by igorspasic** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/27897.<br>:rocket:

**Comment by igorspasic** [comment]
Just started reviewing :)<br>:rocket:

**Comment by igorspasic** [comment]
Just started reviewing :)<br>:rocket:

**Comment by igorspasic** [comment]
Pull request submitted to https://github.com/daviddotzhang/liferay-portal/pull/6. [See changes here.](https://github.com/igorspasic/liferay-portal/compare/aafacd4~1...aafacd4)<br>:rocket:

**Pull request closed without merging**
