### PR TITLE
LPS-56072

### PR DESCRIPTION
**Pull request by alee8888**
https://issues.liferay.com/browse/LPS-56072

### CODE REVIEW

**Comment by alee8888** [comment]
@igorspasic can you please review and see if I missed anything? Thanks again!

**Comment by alee8888** [comment]
ci:retest

**Comment by igorspasic** [comment]
Just started reviewing :)<br>:rocket:

**Comment by igorspasic** [comment]
this is not enough - `app.server.properties` is just one file - we have many things inside the code and the build scripts that are version related.

**Comment by igorspasic** [comment]
Pull request submitted to https://github.com/alee8888/liferay-portal/pull/8. [See changes here.](https://github.com/igorspasic/liferay-portal/compare/a5e4b9a~2...a5e4b9a)<br>:rocket:

**Pull request closed without merging**
