### PR TITLE
LPS-56624 OSGi modules are registered in wrong context root in jsonws services

### PR DESCRIPTION
**Pull request by nhpatt**
Hi Igor! I think I've found a bug when registering OSGi modules as jsonws services. I've talked about this problem with Carlos and he told me to send the pull to you.

The bug manifests as OSGi json services deployed without a slash in their context root and you can't call them by url/curl/mobile generated services... but they are available through invokews.

I think the code thinks that all services are going to start with a slash and OSGi ones start with /o/audiencetargeting (for example).

I've changed the way of calculating the context path based on this commit: https://github.com/liferay/liferay-portal/commit/054af01

Seems Ray has changed the way of calculating it in master but not in 6.2. Still can't work in master but I will send the pull after discussing this one :)

### CODE REVIEW

**Comment by igorspasic** [comment]
Just started reviewing :)<br>:rocket:

**Comment by igorspasic** [comment]
All good, please proceed :)

**Comment by mdelapenya** [comment]
Hey @igorspasic, could you reopen this pull and send it to BChan?

Not sure why, @nhpatt 's pulls are not tested by the CI system. Meanwhile we fix it, we'd need you to send the pull. Could you do it for us please?

Thanks!

**Comment by igorspasic** [comment]
I am not able to reopen this. Can @nhpatt resend PR to me?

**Pull request closed without merging**
