### PR TITLE
[TECHNICAL-SUPPORT] LPS-58586

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @Preston-Crary

### CODE REVIEW

**Comment by igorspasic** [comment]
Just started reviewing :)<br>:rocket:

**Comment by igorspasic** [comment]
Hey @jonathanmccann this is the correct fix.

Only thing is that now all `long`s will be serialized as strings - and not only the IDs. Are we ok with this?

**Comment by Preston-Crary** [comment]
Hi Igor,

@eduardolundgren and I talked about the solution.  We decided to convert all longs to strings since they can not reliably be converted back (in JavaScript) without losing precision. If you can find a way to only convert IDs that might be better.

**Comment by igorspasic** [comment]
I agree @Preston-Crary... we might try to filter via name, like all `PrimaryKey` and `*Id` properties, but essentially we would got the same.

So I am ok with this - I was more wondering on the UI side, if our JavaScripts are ok with the change. I am going to send this PR to Brian.

**Comment by eduardolundgren** [comment]
I would add it to all longs. If we fix only ids the other longs are still broken.

**Comment by igorspasic** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/30282.<br>:rocket:

**Comment by eduardolundgren** [comment]
:+1:

**Pull request closed without merging**
