### PR TITLE
[TECHNICAL SUPPORT] LPS-64698 Fix DeepNamedValueScanner related performance issue

### PR DESCRIPTION
**Pull request by vilmospapp**
Hi @igorspasic,

I've created a little modification in *ServerCapabilities implementations, so it could be overridden manually, whether to use the DeepNamedValueScanner or set the variable to mark the AS to support hotdeploy.

Please review my changes.
Regards,
Vilmos

### CODE REVIEW

**Comment by igorspasic** [comment]
I can't really try much this, but what you said make perfect sense. I would go on with this.

**Comment by vilmospapp** [comment]
ci:retest

**Comment by vilmospapp** [comment]
ci:retest

**Comment by vilmospapp** [comment]
ci:retest

**Comment by vilmospapp** [comment]
ci:retest

**Comment by vilmospapp** [comment]
ci:retest

**Comment by vilmospapp** [comment]
Hi @igorspasic 

Finally it's passed the tests. When you will  have the chance to review it, please do so. We gave out this fix in SDH already.

Regards,
Vilmos

**Comment by rotty3000** [comment]
@vilmospapp can you assign this PR to me?

thanks

**Comment by vilmospapp** [comment]
Hi @rotty3000,

Sure, I'll rebase it and resend it to you.

**Pull request closed without merging**
